- src/Views/Behavior.vala
As per https://github.com/elementary/switchboard-plug-keyboard/issues/99
> Remove ellipsis from "Type to test your settings"

- src/Widgets/Layout/AddLayoutPopover.vala
Dialogs aren't supposed to have window decorations in elementary OS
> Remove decoration close button from gkbd dialog

- src/Widgets/Layout/AddLayoutPopover.vala
Reclaim some vertical space by moving the show layout button inline with other actions in this popover
> Move show layout button into popover action area

- src/Keyboard.vala
Stack switcher buttons are no longer homogeneous width by default in gtk >= 3.20
Do some organization while we're here
> Make stack switcher homogeneous

- src/Views/Layout.vala
Replaces a method with a Gtk.Label subclass. Trying to keep it clear how the layout is actually constructed and not have methods going all over the place touching things they don't need to be touching.
> Layout.vala: replace new label method with class

- src/Keyboard.vala
- src/Views/AbstractPage.vala
* Row and column homogeneous are false by default
* Set margins on the stack (and stack switcher) instead of on each page inside the stack
> AbstractPage.vala: remove unnecessary properties

- src/Views/Layout.vala
* Replaces two switch creation methods with a single class
* Since all switches are the same length, we only need to add one of them to the size group for alignment
This should probably be tested by Korean/Japanese layout users to make certain that these switches still work as expected
> Layout.vala: Replace switch creation methods with class

- src/Shortcuts/Shortcut.vala
Whenever we describe a shortcut in the UI in other places we always use `+` as in `Alt + Tab`, but here we're using `·`. This branch makes it `+`
> Use plus as a separator

- src/Shortcuts/List.vala
Fixes #12 
Removes the toggle magnifier shortcut because that seems to do nothing
> Use Zoom shortcuts from Gala

- src/Shortcuts/List.vala
Fix a couple of regressions introduced in 2c4e20628faf1c7d611f1ac20ab3a55b6c65bc45
* Re-remove the hardcoded GNOME apps stuff
* Fix schemas for zoom
* Fix keys for workspace switching and cycling
> Fix regressions in list.vala

- src/Shortcuts/List.vala
This moves the "Launch Media Player" shortcut to the applications section and renames it to be more specific since it launches Music and not Videos. The old label is a bit ambiguous about which will be opened.
> Move launch music to apps section

- src/Dialogs/ConflictDialog.vala
- src/Widgets/Shortcuts/CustomTree.vala
- src/Widgets/Shortcuts/Tree.vala
* Add a copyright header
* Subclass Granite.MessageDialog instead of Gtk.MessageDialog
* No terminating punctuation in primary text, but yes in secondary text
* Set action button as destructive style class
* Set `transient_for` so that we can center on the parent window
* GObject style
> Rewrite conflict dialog as a Granite.MessageDialog

- src/Views/Layout.vala
Fixes #146 
Relies on https://github.com/elementary/default-settings/pull/9
Adds a combobox to set the overlay key function
> Add setting for overlay key

- src/Views/Layout.vala
This is very tiny thing, but I think we should use "Hankaku Zenkaku" instead of "Zenkaku Hankaku", because the name of that key is "半角／全角キー (Hankaku/Zenkaku Key)", not "全角／半角キー (Zenkaku/Hankaku Key)". (See https://en.wikipedia.org/wiki/Language_input_keys#Half-width/Full-width/Kanji for more detail)
> Use "Hankaku Zenkaku" instead of "Zenkaku Hankaku"

- src/Views/Layout.vala
The "Caps Lock disabled" entry in the Layout tab was inconsistent with the ones in the other menus. This PR changes its label to match the others.
This is a small change in a user-facing label -- the bulk of the edits are the updates to the po files since the old string has been folded into an existing message.
> Change label of disabled caps lock key to match the others

- src/Views/Layout.vala
All the other named keys are spelled out in user-facing messages (`Caps Lock`, `Right Alt`, `Escape`, etc.) but the Control key still used the `Ctrl` abbreviation. This change updates it to be consistent with the others.
Fixes #203.
> Make all labels of the Control key consistent

- src/meson.build
compiler.find_library expects the lib_name without the lib prefix
> meson: correct finding gnomekbdui

- src/Views/Layout.vala
Still needs https://github.com/elementary/wingpanel-indicator-keyboard/pull/62
See https://github.com/elementary/wingpanel-indicator-notifications/pull/110 for details why I need this in NixOS. And docs say that you should pretty much always lookup recursive.
> Layout: lookup io.elementary.wingpanel.keyboard recursive

- src/Shortcuts/Settings.vala
After recent updates, the switchboard keyboard plug crashes on opening.  This appears to be due to some shortcut settings schema keys changing from string array type to simple strings.
This PR checks the VariantType of the key before attempting to retrieve it, which fixes the crash.
> Fix crash on opening due to assuming incorrect key value type

- src/Views/InputMethod.vala
I'm not sure we need to link to IBus settings anymore. It seems like the majority of these settings are already accounted for here and some of the things in this dialog don't apply to Pantheon (like the systray icon")
> InputMethodView: Remove advanced button

- debian/control
Fixes #315 
Switchboard crashes on loading the `keyboard` module without the ibus GSettings schema installed
> control: Runtime dependency on ibus

- src/Views/Layout.vala
⌘ key behavior: [Application menu] in Layout view no longer works because `wingpanel` became `io.elementary.wingpanel`. So this PR simply update the name of the wingpanel binary in the Layout view.
> Fix not working ⌘ key behavior Application Menu

- src/Views/InputMethod.vala
At the moment `remove_button` remains sensitive after you add an new engine from the popover or removing an exiting engine. If you click `remove_button` without any engine is selected, System Settings crashes with segmentation fault. This PR make sure we set sensitivity of `remove_button` correctly.
> InputMethod: Set sensitivity of remove_button correctly

- src/Views/InputMethod.vala
"Candidate window" is this:
And the preference here does not mean it and actually points this called "property panel":
> InputMethod: Fix wrong copy of ibus panel label

- src/Views/InputMethod.vala
Fixes #https://github.com/elementary/wingpanel-indicator-keyboard/issues/105
fixes #379
- When the IBus daemon is started manually a suitable desktop file is added to the user's autostart directory
- Whether autostart is enabled depends on whether there are any input method engines active.
At the moment IBus is not autostarted, even if input method engines are added, unless the user activates the daemon using the "No Daemon" view.
At the moment, Wingpanel has a switch to turn the IBus daemon on and off temporarily but this setting is not remembered between sessions - IBus is still autostarted.  It should be considered whether turning this switch off should disable the autostart file - which would require another PR for wingpanel.
> Ensure IBus daemon autostarts if (and only if) input methods are active

- debian/control
Seems like we should runtime depend on Gala for its settings keys, and also now for the Super key behavior
> Control: Add Gala runtime dep

- src/Views/Layout.vala
Removes empty tooltip on "On-screen keyboard settings…" link button
> Remove empty tooltip

- src/Shortcuts/Settings.vala
- src/Widgets/Shortcuts/ShortcutListBox.vala
This fixes a regression from c4988d9a3ed26e44fe61b3f09bb5dc071497ff4f.
The vanilla GSD does not know about the 'terminal' media-key, this result in a crash for non-ubuntu users. This restores the behavior before c4988d9, we just hide the row when the key is not valid.
https://git.launchpad.net/ubuntu/+source/gnome-settings-daemon/diff/debian/patches/ubuntu/media-keys-restore-terminal-keyboard-shortcut-schema.patch
- Closes https://github.com/elementary/switchboard-plug-keyboard/issues/426
> ShortcutListBox: only add ShortcutRow when schema key is valid

- data/Behavior.css
- data/gresource.xml
- src/Views/Behavior.vala
Removes the spinbuttons. They're super overkill and make things look messy and complicated. I don't think anyone is setting exact millisecond values for these settings. More likely you're fiddling with the slider until it feels okay
> Behavior: Remove spinbuttons

- src/Views/Layout.vala
These are now available in Desktop → Dock & Panel
> Layout: remove panel indicator settings

- src/Widgets/Shortcuts/CustomShortcutListBox.vala
- src/Widgets/Shortcuts/ShortcutListBox.vala
Avoid crash when there are incorrect keyboard shortcuts.
> Check if `Granite.accel_to_string` returns `null`

- src/Views/Shortcuts.vala
* Replace grid with Box
* Use child property
* explicit expands
* rename variables to be less ambiguous (no `scrolledwindow` and `scrolled_window`)
* Construct add button in GTK4 friendly way (make sure screen reader can still read it)
> Shortcuts: GTK4 prep

- src/Widgets/Layout/Display.vala
* Build button with icon and label in GTK4 friendly way, fix screen reader while here
* Actionbar can't have a child in GTK4, use pack_start
* Style class FLAT instead of INLINE_TOOLBAR
> Display: GTK4 prep

- src/InputSources/SourceSettings.vala
- src/Views/InputMethod.vala
- src/Widgets/Layout/Display.vala
- src/Widgets/Shortcuts/CustomShortcutListBox.vala
Can't use `get_children` in GTK4, so use `get_row_at_index` where it makes sense. Use `remove` instead of `destroy` to avoid an infinite loop in GTK 4 where widgets are destroyed but not removed
> Use get_row_at_index

- data/screenshots.svg
- data/windows.svg
- src/Plug.vala
* Use latest screenshot icon
* Update windows icon to fit within current tile size and reflect the layout of modern applications
> Shortcuts: update category icons

- src/Shortcuts/Settings.vala
- src/Shortcuts/ShortcutsList.vala
- src/Views/Shortcuts.vala
An alternative to https://github.com/elementary/switchboard-plug-keyboard/pull/460 and https://github.com/elementary/default-settings/pull/299
Fixes https://github.com/elementary/switchboard-plug-keyboard/issues/472
Closes https://github.com/elementary/triage/issues/18
> Shortcuts: Add "Keyboard Layouts" tab

- src/Behavior/Behavior.vala
- src/InputMethod/InputMethod.vala
- src/Layout/Layout.vala
- src/Plug.vala
- src/Shortcuts/Shortcuts.vala
Make sure we get the floating header when scrolling
> Use AdwToolbarView

- debian/control
We depend on onboard for on screen keyboard setting so make sure we add it as runtime dep
> Control: add runtime onboard dep

- src/Shortcuts/Backend/ShortcutsList.vala
Follow up to https://github.com/elementary/gala/pull/2309
> Use new multitasking view key

- src/Shortcuts/Backend/ConflictsManager.vala
My main motivation was that we use "Refresh" here as "Refresh", but in System we use it as "Check for updates". And since there's no context, Weblate synchronizes these translations. This branch adds context to this shortcut and also adds comments for translator with explanations on what these shortcut are.
> ConflictsManager: Add comments for translators
