src/Widgets/Layout/AddLayoutPopover.vala

Adds a little splash of color to our lives eh

Give the add layout button the suggested action class

---

src/Widgets/Layout/AddLayoutPopover.vala

Get rid of the frame and go edge-to-edge

Make layout popover edge-to-edge

---

src/Widgets/Layout/AddLayoutPopover.vala
src/Widgets/Layout/Display.vala

* Add copyright header
* Code style fixes
* Rewrite toolbar as actionbar
* Rename `AddLayout ()` to `AddLayoutPopover ()` so that it's clear what this is

Display.vala: rewrite toolbar as actionbar

---

src/Layout/AdvancedSettingsPanel.vala
src/Views/AbstractPage.vala
src/Views/Layout.vala
src/Views/Shortcuts.vala
src/Widgets/Shortcuts/SectionSwitcher.vala

This addresses #11 by just making the abstract page column homogeneous.
I believe this is the cleanest solution, really...

Fix Pane Width (#11)

---

src/Views/Behavior.vala

Unfocus the entry

---

src/Shortcuts/List.vala

* no function changes
* only code style

rewrite List.vala

---

src/Views/Shortcuts.vala

* Bump copyright year
* One true brace
* Tabs to space
* no `this`
* brackets where needed
* construct

Shortcuts.vala: Code style

---

src/Widgets/Shortcuts/SectionSwitcher.vala

This lets us navigate from the switcher to the treeview with a right arrow key

Rewrite Switcher as Gtk.ListBox

---

src/Shortcuts/Settings.vala
src/Shortcuts/Shortcut.vala

As per title.
Vapi files left alone.

Change tabs to spaces in Settings.vala and Shortcuts.vala

---

src/Shortcuts/List.vala
src/Views/Shortcuts.vala
src/Widgets/Shortcuts/SectionSwitcher.vala

There's probably a better way to do this in the future, but at least this does it the same way as the names

Add icons to shortcuts sections

---

src/Views/Shortcuts.vala
src/Widgets/Shortcuts/Display.vala

* one true brace
* Explicit scope
* use actionbar
* Organize

Display.vala: Use ActionBar and fix code style

---

src/Views/Layout.vala

Add Menu key as compose option

---

src/Widgets/Shortcuts/Tree.vala

Don't throw conflict dialog if same schema

---

src/meson.build

Add missing libgnomekbdui dep

---

src/Shortcuts/List.vala

Fixes #156.
Adds the PiP shortcut so users can edit it.

Add PiP shortcut

---

src/Views/Layout.vala

Add a link to ibus settings

---

src/Widgets/Layout/AddLayoutPopover.vala

The input language list is very long, a filter could make the UX a bit more friendly.

Add Search input language #170

---

src/Shortcuts/List.vala

Adds the option to set a keybinding to close windows.

---

src/Views/Shortcuts.vala
src/Widgets/Shortcuts/Display.vala
src/Widgets/Shortcuts/SectionSwitcher.vala

Set the first shortcut category as initially selected

---

data/io.elementary.switchboard.keyboard.appdata.xml.in
data/meson.build
po/extra/POTFILES

Change RDNN to io.elementary.switchboard.keyboard

---

src/Config.vala.in
src/Layout/Handler.vala
src/meson.build

PR on behalf of nixpkgs, this has been a problem for us in NixOS
for gnome-desktop [0] and other projects. See aforementioned issue
for more details.
[0]: https://gitlab.gnome.org/GNOME/gnome-desktop/issues/130

Honor XKB_CONFIG_ROOT environment variable, don't hardcode

---

data/io.elementary.switchboard.keyboard.appdata.xml.in

Should be valid according to https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html

Appdata: Add icon name

---

debian/control

It seems like this package only contains translation files, so it seems to make more sense as recommends

Control: Recommend translation files

---

data/io.elementary.switchboard.keyboard.appdata.xml.in

For better display in Feedback and AppCenter

AppData: Add "Settings" to name

---

.github/workflows/release.yml

After #291 this is no longer compatible with Hera/Bionic

Release: Change branch to Odin

---

src/Shortcuts/List.vala

List: Remove high contrast shortcut

---

src/Widgets/Layout/Display.vala

* New code style for properties
* Don't connect popover add signal repeatedly
* Simplify/combine/remove methods
* Fix indentation
* Explicitly mark things private
* Use `var` keyword

Display: misc cleanup

---

src/Shortcuts/List.vala

Shortcuts/List: Rename Play to Play/Pause

---

src/Layout/Handler.vala

* Reduce scope where possible
* Combine single-use methods

Layout/Handler: misc cleanup

---

src/Layout/LayoutSettings.vala

* Explicitly scope properties and methods
* Constructor up top

LayoutSettings: organize, explicit scope

---

src/Widgets/Layout/Display.vala

review with hide whitespace changes

Layout/Display: inline namespace

---

src/Shortcuts/Settings.vala

Fix all keyboard shortcuts are shown as disabled

---

src/Dialogs/AddLayoutDialog.vala

Suggested improvements.
* Adjust back button text and action according to visible child
* Move keyboard drawing button into header and show when appropriate
Action area just used for actions that close dialog.
More obvious way of returning from keyboard drawing to layout list without closing dialog using the existing back button
and headerbox.

Keep header bar when keyboard drawing shown

---

src/Shortcuts/List.vala

To go along with https://github.com/elementary/gala/pull/953, see rationale there.

Rename 'Minimize' to 'Hide'

---

src/Dialogs/AddLayoutDialog.vala

This margin is now provided by the stylesheet

AddLayoutDialog: Remove extra margin

---

src/Shortcuts/Settings.vala
src/Views/Behavior.vala
src/Views/InputMethod.vala
src/Views/Layout.vala
src/Views/Shortcuts.vala

These methods does not seem to be used anymore

Remove unused reset methods

---

src/Widgets/Layout/Display.vala

I guess we should not allow users removing all layouts

Layout: Always have one layout at least

---

src/Views/InputMethod.vala
src/Views/Layout.vala

Fixes: https://github.com/elementary/switchboard-plug-keyboard/issues/190

Expose on-screen keyboard settings on Layout View

---

data/io.elementary.switchboard.keyboard.appdata.xml.in

Release 2.7.0

---

.github/workflows/main.yml
.github/workflows/release.yml
src/Shortcuts/List.vala

Shortcuts/List: move panel-main-menu to Schema.GALA

---

src/Shortcuts/List.vala

Goes with https://github.com/elementary/gala/pull/1411

Read screenshot shortcuts from gala schema

---

src/Views/Shortcuts.vala
src/Widgets/Shortcuts/CustomShortcutListBox.vala

Custom Shortcuts: New add/remove list pattern

---

src/Views/Shortcuts.vala

Make "Add Shortcut" translatable

---

src/InputMethod/Installer/InstallList.vala

Add ibus-rime to InstallList

---

data/gresource.xml
data/windows.svg
src/Shortcuts/List.vala

Not an fd.o icon name and only used here

Gresource windows category icon

---

data/io.elementary.switchboard.keyboard.appdata.xml.in
meson.build

Fixes a crasher in other distros and unblocks the release of Icons

Release 3.1.1

---

src/Views/Behavior.vala

* code style
* Put everything in a clamp
* Use a vertical box for section spacing and each setting group in its own grid

Behavior: modernize code style

---

src/Plug.vala
src/Views/Behavior.vala
src/Views/Layout.vala

Since this doesn't really have anything to do with the keyboard layout, move this to the behavior tab

Behavior: move onboard to the behavior tab

---

src/Widgets/Shortcuts/CustomShortcutListBox.vala
src/Widgets/Shortcuts/ShortcutListBox.vala

Shortcuts: Allow assigning PrintScreen key

---

data/keyboard.metainfo.xml.in

Fixes annoying https://github.com/elementary/wingpanel-indicator-keyboard/issues/108 bug, which is present on every new installed system (from my experience)

3.2.1 release notes

---

src/Widgets/Shortcuts/ShortcutListBox.vala

ShortcutListBox: use EventControllers

---

src/Widgets/InputMethod/EnginesRow.vala

* Box instead of grid
* child property

EnginesRow: GTK 4 prep

---

src/Plug.vala

* Box instead of grid
* code style

Plug.vala: GTK4 prep

---

src/Dialogs/AddLayoutDialog.vala

* Explicit margins and expands
* Use child property
* boxes instead of grids

AddLayoutDialog: GTK4 prep

---

src/Views/InputMethod.vala

* use child property
* actionbar pack_start instead of add
* Replace grid with box
* explicit margin

InputMethod: GTK4 prep

---

src/Widgets/InputMethod/AddEnginesPopover.vala

* Explicit margins and expands
* Use listbox activate instead manual buttonpress listening
* Child property
* Replace buttonbox with Box
* dialog.present

AddEnginesPopover: GTK4 prep

---

data/meson.build

Meson: install gschema under RDNN

---

src/Widgets/Shortcuts/CustomShortcutListBox.vala

* Replace grids with boxes
* Explicit margins
* Code style
* child property

CustomShortcutListBox: GTK4 prep

---

src/Views/Shortcuts.vala
src/Widgets/Shortcuts/CustomShortcutListBox.vala
src/Widgets/Shortcuts/ShortcutListBox.vala

Can't subclass ListBox in GTK 4, so pack them in a box

ListBoxes: don't subclass listbox

---

src/Shortcuts/Backend/Settings.vala
src/Shortcuts/Backend/ShortcutsList.vala

Goes with elementary/dock#245
They show up but didn't test because of #512 
Also the phrasing might need some improvement :)

Shortcuts: Allow configuring keybinds for launching dock items

---

src/Shortcuts/Backend/Settings.vala

https://github.com/elementary/gala/pull/2032

Use new keybindings schema

---

debian/control

Merge after https://github.com/elementary/gala/pull/2359

Move gala to recommends

---

data/keyboard.metainfo.xml.in
meson.build

Release 8.1.0
